#!/usr/bin/env node
/**
 * Regenerates sitemap.xml from articles.json plus the fixed page list below.
 *
 * Hand-maintaining the sitemap is how it drifted before: it listed a
 * portfolio.html that never existed, pointed every URL at a .html extension
 * that 301-redirects, and omitted /accessibility, both /services sub-pages,
 * and the whole blog. Generating it makes that class of drift impossible.
 *
 * Scheduling is respected: a future-dated article is not yet published, so it
 * is left out. Listing it would point Google at a URL that 404s. This is why
 * the workflow also runs on a daily schedule — when a scheduled post's date
 * arrives, the next run adds it without anyone pushing anything.
 *
 * lastmod is emitted ONLY where the date is genuinely known: article URLs
 * (from articles.json) and the blog index (the newest post's date). Static
 * pages get no lastmod, because this repo doesn't contain index.php,
 * contact.php and friends, so their real modification dates are unknowable
 * from here.
 *
 * An earlier version stamped today's date on every static page. Combined with
 * the daily run that produced a commit every day claiming the whole site had
 * just changed — noise in the history, and a lastmod signal Google learns to
 * distrust precisely because it is always "today". Omitting the field is
 * honest and lets Google fall back to its own crawl heuristics.
 *
 * Usage:  node tools/sitemap/generate.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const BASE = 'https://jindrawebdev.com';

// thank-you.php is deliberately absent: it sets noindex.
// send-contact.php and sms-signup.php are POST handlers, not pages.
const STATIC_PAGES = [
  { loc: '/', changefreq: 'weekly', priority: '1.0' },
  { loc: '/services', changefreq: 'monthly', priority: '0.9' },
  { loc: '/services/website-design/', changefreq: 'monthly', priority: '0.8' },
  { loc: '/services/local-seo/', changefreq: 'monthly', priority: '0.8' },
  { loc: '/services/drone-photography/', changefreq: 'monthly', priority: '0.8' },
  { loc: '/services/brand-design/', changefreq: 'monthly', priority: '0.8' },
  { loc: '/services/digital-cleanup/', changefreq: 'monthly', priority: '0.8' },
  { loc: '/blog', changefreq: 'weekly', priority: '0.9' },
  { loc: '/about', changefreq: 'monthly', priority: '0.8' },
  { loc: '/contact', changefreq: 'monthly', priority: '0.8' },
  { loc: '/privacy', changefreq: 'yearly', priority: '0.3' },
  { loc: '/terms', changefreq: 'yearly', priority: '0.3' },
  { loc: '/accessibility', changefreq: 'yearly', priority: '0.3' },
];

const today = new Date().toISOString().slice(0, 10);

const data = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'blog-data/articles.json'), 'utf8')
);

const published = data.articles
  .filter((a) => a.datePublished <= today)
  .sort((a, b) => (a.datePublished < b.datePublished ? 1 : -1));

const skipped = data.articles.length - published.length;

// The blog index changes whenever the newest post does.
const newestPost = published.length ? published[0].datePublished : today;

const entries = [];
for (const p of STATIC_PAGES) {
  entries.push({
    loc: BASE + p.loc,
    // Only the blog index has a knowable date: its newest post.
    lastmod: p.loc === '/blog' ? newestPost : null,
    changefreq: p.changefreq,
    priority: p.priority,
  });
  // Keep article URLs grouped directly beneath the blog index.
  if (p.loc === '/blog') {
    for (const a of published) {
      entries.push({
        loc: `${BASE}/blog/${a.slug}`,
        lastmod: a.dateModified || a.datePublished,
        changefreq: 'monthly',
        priority: '0.7',
      });
    }
  }
}

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  `  <!-- Generated by tools/sitemap/generate.js — edits here will be overwritten. -->\n\n` +
  entries
    .map(
      (e) =>
        `  <url>\n` +
        `    <loc>${e.loc}</loc>\n` +
        (e.lastmod ? `    <lastmod>${e.lastmod}</lastmod>\n` : '') +
        `    <changefreq>${e.changefreq}</changefreq>\n` +
        `    <priority>${e.priority}</priority>\n` +
        `  </url>\n`
    )
    .join('\n') +
  `\n</urlset>\n`;

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml);

console.log(`sitemap.xml: ${entries.length} URLs (${published.length} articles)`);
if (skipped) {
  console.log(`  ${skipped} future-dated article(s) omitted until their publish date`);
}
