---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lexiizgf/jindrawebdev.com/
    - /bin/cp -R blog.php $DEPLOYPATH
    - /bin/cp -R article.php $DEPLOYPATH
    - /bin/cp -R blog-data $DEPLOYPATH
