---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lexiizgf/jindrawebdev.com/
    - /bin/cp -R blog.php $DEPLOYPATH
    - /bin/cp -R article.php $DEPLOYPATH
    - /bin/cp -R about.php $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/services
    - /bin/cp -R services/index.php $DEPLOYPATH/services/index.php
    - /bin/mkdir -p $DEPLOYPATH/services/local-seo
    - /bin/cp -R services/local-seo/index.php $DEPLOYPATH/services/local-seo/index.php
    - /bin/mkdir -p $DEPLOYPATH/services/website-design
    - /bin/cp -R services/website-design/index.php $DEPLOYPATH/services/website-design/index.php
    - /bin/mkdir -p $DEPLOYPATH/services/drone-photography
    - /bin/cp -R services/drone-photography/index.php $DEPLOYPATH/services/drone-photography/index.php
    - /bin/mkdir -p $DEPLOYPATH/services/brand-design
    - /bin/cp -R services/brand-design/index.php $DEPLOYPATH/services/brand-design/index.php
    - /bin/mkdir -p $DEPLOYPATH/services/digital-cleanup
    - /bin/cp -R services/digital-cleanup/index.php $DEPLOYPATH/services/digital-cleanup/index.php
    - /bin/cp -R blog-data $DEPLOYPATH
    - /bin/cp -R sitemap.xml $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/css
    - /bin/cp -R css/tailwind.min.css $DEPLOYPATH/css/tailwind.min.css
    - /bin/mkdir -p $DEPLOYPATH/css/fonts
    - /bin/cp -R css/fonts/. $DEPLOYPATH/css/fonts/
    - /bin/mkdir -p $DEPLOYPATH/images/blog
    - /bin/cp -R images/blog/. $DEPLOYPATH/images/blog/
    - /bin/mkdir -p $DEPLOYPATH/includes
    - /bin/cp -R includes/header.php $DEPLOYPATH/includes/header.php
    - /bin/cp -R includes/footer.php $DEPLOYPATH/includes/footer.php
